### ISSUE TITLE
Importing keypairs by private key only.

### ISSUE THREAD

**Issue by TheAwiteb** [TheAwiteb/solwalrs#7]
I think the private key is safest to use than the mnemonic

### Subtasks
- [x] When importing a keypair, check if the it's 32 bytes or 64 bytes, if it's 64 bytes, then it's a encoded keypair, if it's 32 bytes, then it's a private key only.
- [x] When importing a keypair, check if it's a array of bytes or a string (then check if it's 32 bytes or 64 bytes).
- [x] Also check if it's already exists
